openapi: 3.0.3
info:
  title: Calculator Service
  description: HTTP service for multiplying numbers, a goa teaser
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /multiply/:
    post:
      tags:
      - calc
      summary: multiply calc
      operationId: calc#multiply
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultiplyRequestBody'
            example:
              anyobject:
                ob:
                  ok: 1
                  testk: testl
                test: 10
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 8803302123552712831
                format: int64
              example: 5401762099778430809
components:
  schemas:
    MultiplyRequestBody:
      type: object
      properties:
        anyobject:
          type: object
          description: pass any json object
          example:
            ob:
              ok: 1
              testk: testl
            test: 10
          additionalProperties:
            type: string
            example: Eos qui exercitationem sed non.
            format: binary
      example:
        anyobject:
          ob:
            ok: 1
            testk: testl
          test: 10
      required:
      - anyobject
tags:
- name: calc
  description: The calc service performs operations on numbers
